version: 1.0.{build}
build_script:
- ps: >-
    dotnet restore

    dotnet build -c Release SeaOrDew.sln /property:VersionPrefix=$env:APPVEYOR_BUILD_VERSION

    ./Coverage.ps1

    ./Coveralls.ps1

    dotnet pack -c Release -o ${pwd} .\src\csMACnz.SeaOrDew\csMACnz.SeaOrDew.csproj /property:VersionPrefix=$env:APPVEYOR_BUILD_VERSION
test: off
artifacts:
- path: csMACnz.SeaOrDew.*.nupkg
  name: nuget   